juser0719/LTF2_FE

.github/workflows/build.yml
github actions event trigger 변경
PR 타입 명시
- 이슈 PR 첨부
pull request 로 github actions를 trigger하면 secrets repository에 접근 못하게 되는 현상 발견.
github secrets에서는 보안을 위해 접근을 제한한 것을 확인.
따라서 pull_request가 됐을 때 base repository를 기준으로 trigger가 되게 만듦
[참고 link](https://blog.outsider.ne.kr/1541)
=> [LTS-53] modify event trigger

client/package-lock.json, client/package.json, client/src/components/CartBar.jsx, client/src/components/CartProduct.jsx, client/src/components/TitleSection.jsx, client/src/pages/Cart.jsx, client/src/styles/cartStyle.js, client/src/styles/titleSectionStyle.js
- 장바구니 화면 구성
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부
=> [LT2-30] 장바구니 화면 구성

.github/workflows/build.yml
들여쓰기 수정
PR 타입 명시
- 이슈 PR 첨부
script syntax 오류 수정하여 PR
=> [LTS-53] script syntax수정

.github/workflows/build.yml
if merged 조건 삭제
PR 타입 명시
추후 업로드 예정..
if merge는 pull_request event에서만 의미 있는 조건. 따라서 pull_request_target이라는 event와는 애초에 맞지 않았음.
따라서 해당 조건을 삭제
=> [LTS-53] script trigger와 조건 수정

.github/workflows/build.yml
주석 제거
PR 타입 명시
github actions가 무시되는 현상 발생. script도 이전 사항으로 반영이 되는 상황.
=> [LTS-53] 주석제거

client/src/App.jsx, client/src/components/CartProduct.jsx, client/src/pages/Cart.jsx
- 장바구니 삭제 버튼 활성화
- 쿠키에 데이터가 없을 시 데이터 보이지 않도록 수정
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부
=> [LT2-17] 장바구니 삭제버튼 및 버그 수정

client/src/App.jsx, client/src/components/NavBar.jsx, client/src/components/PhoneList.jsx, client/src/components/SearchBar.jsx, client/src/components/SearchResult.jsx, client/src/components/SearchResultCount.jsx, client/src/pages/Search.jsx, client/src/styles/barStyle.js, client/src/styles/phoneListStyle.js, client/src/styles/searchBarStyle.js, client/src/styles/searchResultCountStyle.js, client/src/styles/searchResultStyle.js, client/src/styles/searchStyle.js
- Search 관련 UI 및 Navbar, SearchPage 기능 개발
PR 타입 명시
돋보기 눈치싸움에 근본적인 해결책이 필요하다.
- 이슈 PR 첨부
=> [LT2-60] Search 관련 UI 및 기능 개발

client/src/components/NavBar.jsx, client/src/components/NavMap.jsx, client/src/styles/barStyle.js
- navbar slide menu ui 개발
PR 타입 명시
=> [LT2-28] navbar slide menu ui 개발

client/src/api/PhoneAPI.jsx, client/src/api/PlanAPI.jsx, client/src/api/PublicSupportAPI.jsx, client/src/api/SearchAPI.jsx, client/src/api/index.jsx, client/src/pages/Cart.jsx
- axios api
- phone, plan, public-support, search 추가
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부
=> [LT2-30] axios api

client/src/api/PhoneAPI.jsx, client/src/api/PlanAPI.jsx, client/src/api/PublicSupportAPI.jsx, client/src/api/SearchAPI.jsx
- axios return type 설정
- 오류 발생시 {상태코드, 메세지} 형식으로 리턴하도록 바꾸었습니다
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부
=> [LT2-30] axios api catch return type

.github/workflows/build-in-forked.yml, .github/workflows/deploy.yml
dev branch 배포 장소 변경에 따른 환경변수 변경
PR 타입 명시
=> [LT2-53] modify front dev branch ci cd deployment

client/src/App.jsx, client/src/components/Phone.jsx, client/src/components/SearchResult.jsx, client/src/pages/Search.jsx
- 검색 관련 bug hotfix
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부
=> [LT2-44] 검색 관련 bug fix

client/src/App.jsx, client/src/components/ComparedModal.jsx, client/src/components/ComparedPopup.jsx, client/src/components/DataOptSelect.jsx, client/src/components/DetailInfomation.jsx, client/src/components/Phone.jsx, client/src/components/SideFlexRow.jsx, client/src/methods/inputCompare.js, client/src/methods/priceCalc.js, client/src/pages/Detail.jsx, client/src/styles/detailInfoStyle.js
- 요금 계산 메소드
PR 타입 명시
추후 비교 UI 완성 예정
=> [LT2-67] 요금 계산 메소드

client/src/App.jsx, client/src/components/CartProduct.jsx, client/src/pages/Cart.jsx
- 동기화 빼고 버그 수정
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부
=> [LT2-30] 장바구니 버그 수정

client/src/App.jsx, client/src/components/ComparedModal.jsx, client/src/components/ComparedModalDetailBox.jsx, client/src/components/ComparedModalPhoneBox.jsx, client/src/components/ComparedModalSelectBox.jsx, client/src/components/ComparedModalSpecBox.jsx, client/src/components/ComparedPopup.jsx, client/src/components/DataOptSelect.jsx, client/src/components/DetailInfomation.jsx, client/src/components/DetailSideBar.jsx, client/src/components/Header.jsx, client/src/components/NavBar.jsx, client/src/components/NotFound.jsx, client/src/methods/inputCompare.js, client/src/methods/priceCalc.js, client/src/pages/Detail.jsx, client/src/pages/Main.jsx, client/src/pages/Order.jsx, client/src/styles/compareStyle.js, client/src/styles/mainStyle.js
- 비교창 기능 개발 및 data fetching
PR 타입 명시
=> [LT2-45] 비교창 기능 개발 및 data fetching

client/.env.production, client/src/api/index.jsx, client/src/components/SearchResult.jsx, client/src/pages/Search.jsx, client/src/styles/searchStyle.js
- base url 설정
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부
=> [LT2-44] Search 비교하기 기능 및 base url 설정

client/src/components/CartProduct.jsx
- 보내는 데이터 추가
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부
=> [LT2-30] 가입하기 state 데이터 추가

.github/workflows/deploy.yml, client/conf/conf.d/default.conf
- nginx conf에 proxy pass 추가
- aws 정보 수정
PR 타입 명시
=> [LT2-53] modify front dev deploy

client/src/App.jsx, client/src/components/CartProduct.jsx, client/src/pages/Cart.jsx
- 장바구니 비교하기 기능, 메인페이지 이동 추가
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부
=> [LT2-30] 비교하기 기능 및 메인페이지 이동 추가

.github/workflows/deploy.yml, client/conf/conf.d/default.conf
- nginx & backend 연결 테스트
PR 타입 명시
=> [LT2-53] add nginx proxy server name

.github/workflows/deploy.yml
=> [LT2-53] for front end deploy checking commit

.github/workflows/deploy.yml
- ECS에서 로드 밸런서를 service에 추가하기 위해 service재생성. service name 변경됨. 따라서 actions script변경
PR 타입 명시
=> [LT2-53] add front ecs service load balancer

client/public/index.html, client/public/manifest.json, client/src/components/CartProduct.jsx, client/src/components/DetailInfomation.jsx, client/src/components/DetailSideBar.jsx, client/src/components/Filter.jsx, client/src/components/NavBar.jsx, client/src/components/NoResult.jsx, client/src/components/OrderBar.jsx, client/src/components/Phone.jsx, client/src/components/PhoneInfomation.jsx, client/src/components/PhoneList.jsx, client/src/components/PlanModal.jsx, client/src/components/RangeSlider.jsx, client/src/components/SearchResult.jsx, client/src/pages/Detail.jsx, client/src/pages/Home.jsx
=> 디테일 페이지 세부 수정

client/src/components/OrderUserInfoForm.jsx, client/src/util/validator.js
- "주문완료" -> "주문 완료" 로 valitator 체크 못했음
PR 타입 명시
=> Order Error fix

client/src/api/index.jsx
- 어떤 점이 바뀐건지 짧게 설명 
- (UI 변경있다면) 스크린샷 첨부
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부
=> [LT2-52] modify base url

client/src/components/DetailInfomation.jsx, client/src/components/NavBar.jsx, client/src/components/PhoneInfomation.jsx, client/src/components/PlanBox.jsx, client/src/components/PlanBoxModal.jsx, client/src/components/PlanModal.jsx, client/src/pages/Detail.jsx, client/src/pages/Size.jsx, client/src/styles/sizeStyle.js
- 디테일 페이지 요금제 카드에서 + 클릭 시 상세 내용 모달 등장
- 실물 크기 측정 페이지에서 모니터 사이즈 직접 입력 기능 추가
- 위 변경 사항에 따른 적용해야 하는 사항들 적용
PR 타입 명시
=> 디테일 페이지 및 실물 크기 측정 기능 추가

.github/workflows/deploy.yml, client/conf/conf.d/default.conf
- 이전에는 front / back 연결이 안됐음. NGINX proxy pass의 설정을 localhost -> docker ip로 변경하여 해결
PR 타입 명시
=> [LT-53] NGINX proxy pass 설정 완료

client/src/App.jsx, client/src/api/index.jsx, client/src/assets/navMapData.js, client/src/components/DetailSideBar.jsx, client/src/components/Filter.jsx, client/src/components/NavBar.jsx, client/src/components/NoResult.jsx, client/src/components/Phone.jsx, client/src/components/PhoneInfomation.jsx, client/src/components/PhoneList.jsx, client/src/components/PlanBoxModal.jsx, client/src/components/PlanModal.jsx, client/src/pages/Detail.jsx, client/src/pages/Home.jsx, client/src/styles/barStyle.js, client/src/util/goToCart.js, client/src/util/priceCalc.js, client/src/util/sortPhoneList.js
=> filter fix

client/src/pages/Home.jsx
- sort hot fix
- (UI 변경있다면) 스크린샷 첨부
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부
=> sort hot fix

client/src/components/NoResult.jsx, client/src/components/OrderUserInfoForm.jsx, client/src/pages/Home.jsx
- Order Error fix && Filter reset
PR 타입 명시
=> Order Error fix && Filter reset

client/src/components/PlanModal.jsx, client/src/components/SearchBar.jsx, client/src/components/SearchResult.jsx, client/src/components/SearchResultCount.jsx, client/src/pages/Main.jsx, client/src/pages/Search.jsx, client/src/styles/mainStyle.js, client/src/styles/planStyle.js, client/src/styles/searchBarStyle.js, client/src/styles/searchResultCountStyle.js, client/src/styles/searchResultStyle.js, client/src/styles/searchStyle.js
- 작성한 부분 주석 달기
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부
=> 작성한 부분 주석 달기

client/src/components/OrderUserInfoForm.jsx, client/src/components/PlanModal.jsx
=> plan modal hot fix

client/src/components/CartProduct.jsx
- 1개월 할부 -> 일시불
PR 타입 명시
추후 업로드 예정..
- 이슈 PR 첨부
=> cart hotfix

client/src/components/CartProduct.jsx, client/src/components/Phone.jsx
=> compare hotfix
